### ISSUE TITLE
[FEATURE] 게시판 디테일 구현

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#1]
## 🌴 작업 브랜치 
`feature/#1`

## 💼 TASK 개요 
- 게시판 관련 디테일 사항 체크

## ✅ TODO 및 진행현황 

- [x] 마우스 호버시 액션
- [x] JSON 기반 더미 데이터 구현
- [x] 더미 데이터 기반 표현
- [x] 인피니트 스크롤링
