### ISSUE TITLE
[FEATURE] 게시글 조회 API 연동

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#17]
## 🌴 작업 브랜치 
`feature/#17`

## 💼 TASK 개요 
게시글 조회 API 연동

## ✅ TODO 및 진행현황 

- [ ] 헤더 프로필 이미지 GET 연동
- [ ] 게시글 조회 GET 연동
- [ ] 세션 전송 확인
