### ISSUE TITLE
[REFACTOR] ES6 문법 적용

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#41]
## 🌴 작업 브랜치 
`feature/#41`

## 💼 TASK 개요 
ES6 문법 기반 리팩토링 도입

## ✅ TODO 및 진행현황 

- [x] import, export 기반으로 변경
- [x] 화살표 함수로 변경
- [x] var 변수 제거
