### ISSUE TITLE
[BUG] 회원가입 유효성 검사 완료 후 색상 미변경

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#45]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 회원가입 모든 필드 작성 후 유효성 검사 통과한 뒤, 회원가입 버튼 색상이 변경되지 않음

## TODO

- [ ] 유효성 검사 통과시 색상 변경 코드 추가
