### ISSUE TITLE
[BUG] 조회수 증가 오류

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#47]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 좋아요 업데이트시 조회수 증가하는 버그 발생
- 조회수 업데이트하는 서버 로직 분리
- 서버 연결 API 또한 로직 분리

## TODO

- [ ] 조회수 증가 버그 수정
