### ISSUE TITLE
[BUG] 댓글 길이에 따른 CSS 변화 발생

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#49]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 댓글 길이에 따른 CSS 어긋남 발생
- 해당 부분 수정

## TODO

- [ ] 댓글 길이 고정 세팅
