### ISSUE TITLE
[BUG] 유효성 검증 후 미통과시에도 요청 전송되는 버그

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#51]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 유효성 검증 후 isValid가 false임에도 불구하고 서버로 요청이 전송되는 현상

## TODO

- [ ] 유효성 검증 필요한 부분 모두 점검
- [ ] 해당 부분 로직 변경
