### ISSUE TITLE
[BUG] 작성 시간 한국 시간대로 맞춰주기

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#60]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## BUG 개요

- 글이나 댓글 작성시 데이터베이스에는 현재 시간대로 잘 저장되지만, Get해올 때 Docker 내부 시간대 기준으로 변경되어 나타나는 오류

## TODO

- [ ] 작성 시간 한국 시간대로 변경하는 코드 Dockerfile에 추가
