### ISSUE TITLE
[FEATURE] 댓글 수정 기능, 삭제 모달 기능 추가

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#7]
## 🌴 작업 브랜치 
`feature/#7`

## 💼 TASK 개요 
- 댓글 관련 추가 안된 기능들 추가
- 자잘한 오류 해결

## ✅ TODO 및 진행현황 

- [x] 댓글 수정 기능 구현
- [x] 댓글 삭제 선택시 모달창 안뜨는 오류 해결
- [x] 댓글 밑부분 여백 없는 css 수정
