### ISSUE TITLE
[FEATURE] 회원정보조회 Fetch, Event 추가

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-fe#8]
## 🌴 작업 브랜치 
`feature/#8`

## 💼 TASK 개요 
- 회원정보수정시 조회된 회원정보조회 Fetch 및 관련 event 추가

## ✅ TODO 및 진행현황 

- [x] 회원정보조회 Fetch 추가
- [x] 드롭다운 hover시 배경색 변경 필요
- [x] 수정 완료 버튼 클릭시 토스트메세지 기능 추가
- [x] 회원탈퇴 완료시 로그인 페이지 이동 이벤트
- [x] 각종 버튼 hover 색상 변경 추가
- [x] 프로필 사진 추가 기능
